"""Local context resolution for execution plans.

This module resolves the "inherited/injected" fields of an execution plan:
- user_context: from session/authentication
- scope: from policy/deployment configuration
- constraints: from policy rules
- invariants: from policy rules

These fields are NOT generated by the LLM - they come from the local
environment where the plan will execute.

TODO(nayname): Add unit tests — see PR #16 review.
Minimum coverage needed:
  - LocalContext loading/parsing
  - LocalContextResolver validation
  - PolicyProvider error handling
  - Integration with governance models
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol

from .models import (
    ApprovalModel,
    Constraints,
    DataSensitivity,
    Invariants,
    RequireApproval,
    Scope,
    TrustLevel,
    UserContext,
)


class SessionProvider(Protocol):
    """Protocol for session/auth data."""

    @property
    def user_id(self) -> str: ...

    @property
    def role(self) -> str | None: ...

    @property
    def trust_level(self) -> str | None: ...

    @property
    def team(self) -> str | None: ...

    @property
    def access_tier(self) -> str | None: ...

    @property
    def domain(self) -> str | None: ...

    @property
    def oncall(self) -> bool: ...


class PolicyProvider(Protocol):
    """Protocol for policy data."""

    @property
    def target_system(self) -> str: ...

    @property
    def environment(self) -> str: ...

    @property
    def allowed_systems(self) -> list[str]: ...

    @property
    def forbidden_systems(self) -> list[str]: ...

    @property
    def max_total_operations(self) -> int: ...

    @property
    def max_duration_ms(self) -> int: ...

    @property
    def require_sequential(self) -> bool: ...

    @property
    def forbidden_paths(self) -> list[str]: ...

    @property
    def forbidden_commands(self) -> list[str]: ...

    @property
    def forbidden_urls(self) -> list[str]: ...

    @property
    def data_sensitivity(self) -> str | None: ...

    @property
    def approval_model(self) -> str: ...

    @property
    def incident_reference_required(self) -> bool: ...

    @property
    def ticket_reference_required(self) -> bool: ...

    @property
    def must_hold_invariants(self) -> list[str]: ...

    @property
    def preconditions(self) -> list[str]: ...

    @property
    def refusal_conditions(self) -> list[str]: ...


@dataclass
class LocalContext:
    """Resolved local context for plan injection."""

    user_context: UserContext
    scope: Scope
    constraints: Constraints
    invariants: Invariants


class LocalContextResolver:
    """Resolves local context from session and policy providers."""

    def resolve(
        self,
        session: SessionProvider,
        policy: PolicyProvider,
    ) -> LocalContext:
        """Resolve all inherited/injected fields.

        Args:
            session: Session/auth data provider.
            policy: Policy rules provider.

        Returns:
            LocalContext with user_context, scope, constraints, invariants.
        """
        return LocalContext(
            user_context=self._resolve_user_context(session),
            scope=self._resolve_scope(policy),
            constraints=self._resolve_constraints(policy),
            invariants=self._resolve_invariants(policy),
        )

    def _resolve_user_context(self, session: SessionProvider) -> UserContext:
        """Resolve user context from session."""
        trust = None
        if session.trust_level:
            trust = TrustLevel(session.trust_level)

        return UserContext(
            actor_id=session.user_id,
            role=session.role,
            trust_level=trust,
            team=session.team,
            access_tier=session.access_tier,
            domain=session.domain,
            oncall=session.oncall,
        )

    def _resolve_scope(self, policy: PolicyProvider) -> Scope:
        """Resolve scope from policy."""
        return Scope(
            target_system=policy.target_system,
            environment=policy.environment,
            allowed_systems=policy.allowed_systems,
            forbidden_systems=policy.forbidden_systems,
        )

    def _resolve_constraints(self, policy: PolicyProvider) -> Constraints:
        """Resolve constraints from policy."""
        sensitivity = None
        if policy.data_sensitivity:
            sensitivity = DataSensitivity(policy.data_sensitivity)

        return Constraints(
            allow_unplanned=False,  # Always false
            max_total_operations=policy.max_total_operations,
            max_duration_ms=policy.max_duration_ms,
            require_sequential=policy.require_sequential,
            forbidden_paths=policy.forbidden_paths,
            forbidden_commands=policy.forbidden_commands,
            forbidden_urls=policy.forbidden_urls,
            data_sensitivity=sensitivity,
            require_approval=RequireApproval(
                model=ApprovalModel(policy.approval_model),
                incident_reference_required=policy.incident_reference_required,
                ticket_reference_required=policy.ticket_reference_required,
            ),
        )

    def _resolve_invariants(self, policy: PolicyProvider) -> Invariants:
        """Resolve invariants from policy."""
        return Invariants(
            must_hold=policy.must_hold_invariants,
            preconditions=policy.preconditions,
            refusal_conditions=policy.refusal_conditions,
        )


# --- Simple Implementations for Testing ---


@dataclass
class SimpleSession:
    """Simple session implementation for testing."""

    user_id: str
    role: str | None = None
    trust_level: str | None = None
    team: str | None = None
    access_tier: str | None = None
    domain: str | None = None
    oncall: bool = False


@dataclass
class SimplePolicy:
    """Simple policy implementation for testing."""

    target_system: str = "filesystem"
    environment: str = "development"
    allowed_systems: list[str] | None = None
    forbidden_systems: list[str] | None = None
    max_total_operations: int = 50
    max_duration_ms: int = 300000
    require_sequential: bool = False
    forbidden_paths: list[str] | None = None
    forbidden_commands: list[str] | None = None
    forbidden_urls: list[str] | None = None
    data_sensitivity: str | None = None
    approval_model: str = "none"
    incident_reference_required: bool = False
    ticket_reference_required: bool = False
    must_hold_invariants: list[str] | None = None
    preconditions: list[str] | None = None
    refusal_conditions: list[str] | None = None

    def __post_init__(self):
        # Convert None to empty lists
        if self.allowed_systems is None:
            self.allowed_systems = []
        if self.forbidden_systems is None:
            self.forbidden_systems = []
        if self.forbidden_paths is None:
            self.forbidden_paths = []
        if self.forbidden_commands is None:
            self.forbidden_commands = []
        if self.forbidden_urls is None:
            self.forbidden_urls = []
        if self.must_hold_invariants is None:
            self.must_hold_invariants = []
        if self.preconditions is None:
            self.preconditions = []
        if self.refusal_conditions is None:
            self.refusal_conditions = []
